"""Canonical SWADE equipment catalog seed data."""

import sqlite3

CANONICAL_CATALOG_ITEMS = [
    # Melee Weapons
    {
        "name": "Dagger",
        "category": "Melee Weapon",
        "cost": 25.0,
        "weight": 1.0,
        "min_str": "d4",
        "damage": "Str+d4",
        "range": None,
        "armor_bonus": 0,
        "parry_bonus": 0,
        "notes": "",
    },
    {
        "name": "Short Sword",
        "category": "Melee Weapon",
        "cost": 100.0,
        "weight": 4.0,
        "min_str": "d6",
        "damage": "Str+d6",
        "range": None,
        "armor_bonus": 0,
        "parry_bonus": 0,
        "notes": "",
    },
    {
        "name": "Long Sword",
        "category": "Melee Weapon",
        "cost": 300.0,
        "weight": 8.0,
        "min_str": "d8",
        "damage": "Str+d8",
        "range": None,
        "armor_bonus": 0,
        "parry_bonus": 0,
        "notes": "",
    },
    {
        "name": "Battle Axe",
        "category": "Melee Weapon",
        "cost": 300.0,
        "weight": 10.0,
        "min_str": "d8",
        "damage": "Str+d8",
        "range": None,
        "armor_bonus": 0,
        "parry_bonus": 0,
        "notes": "",
    },
    {
        "name": "Greatsword",
        "category": "Melee Weapon",
        "cost": 400.0,
        "weight": 12.0,
        "min_str": "d10",
        "damage": "Str+d10",
        "range": None,
        "armor_bonus": 0,
        "parry_bonus": 0,
        "notes": "Two hands",
    },
    {
        "name": "Spear",
        "category": "Melee Weapon",
        "cost": 100.0,
        "weight": 5.0,
        "min_str": "d6",
        "damage": "Str+d6",
        "range": None,
        "armor_bonus": 0,
        "parry_bonus": 0,
        "notes": "Reach 1",
    },
    # Ranged Weapons
    {
        "name": "Bow",
        "category": "Ranged Weapon",
        "cost": 250.0,
        "weight": 3.0,
        "min_str": "d6",
        "damage": "2d6",
        "range": "12/24/48",
        "armor_bonus": 0,
        "parry_bonus": 0,
        "notes": "",
    },
    {
        "name": "Crossbow",
        "category": "Ranged Weapon",
        "cost": 250.0,
        "weight": 7.0,
        "min_str": "d6",
        "damage": "2d6",
        "range": "15/30/60",
        "armor_bonus": 0,
        "parry_bonus": 0,
        "notes": "AP 2",
    },
    {
        "name": "Glock 9mm",
        "category": "Ranged Weapon",
        "cost": 200.0,
        "weight": 3.0,
        "min_str": "d4",
        "damage": "2d6",
        "range": "12/24/48",
        "armor_bonus": 0,
        "parry_bonus": 0,
        "notes": "AP 1, Semi-Auto",
    },
    {
        "name": "Colt .45",
        "category": "Ranged Weapon",
        "cost": 200.0,
        "weight": 4.0,
        "min_str": "d4",
        "damage": "2d6+1",
        "range": "12/24/48",
        "armor_bonus": 0,
        "parry_bonus": 0,
        "notes": "AP 1, Revolver",
    },
    # Armor
    {
        "name": "Leather Jacket",
        "category": "Armor",
        "cost": 80.0,
        "weight": 5.0,
        "min_str": "d4",
        "damage": None,
        "range": None,
        "armor_bonus": 1,
        "parry_bonus": 0,
        "notes": "Covers Torso, Arms",
    },
    {
        "name": "Chainmail",
        "category": "Armor",
        "cost": 500.0,
        "weight": 25.0,
        "min_str": "d8",
        "damage": None,
        "range": None,
        "armor_bonus": 2,
        "parry_bonus": 0,
        "notes": "Covers Torso, Arms, Legs",
    },
    {
        "name": "Plate",
        "category": "Armor",
        "cost": 700.0,
        "weight": 30.0,
        "min_str": "d10",
        "damage": None,
        "range": None,
        "armor_bonus": 3,
        "parry_bonus": 0,
        "notes": "Full Plate",
    },
    # Shields
    {
        "name": "Small Shield",
        "category": "Shield",
        "cost": 50.0,
        "weight": 4.0,
        "min_str": "d4",
        "damage": None,
        "range": None,
        "armor_bonus": 0,
        "parry_bonus": 1,
        "notes": "+1 Parry",
    },
    {
        "name": "Medium Shield",
        "category": "Shield",
        "cost": 100.0,
        "weight": 8.0,
        "min_str": "d6",
        "damage": None,
        "range": None,
        "armor_bonus": 0,
        "parry_bonus": 2,
        "notes": "+2 Parry, -2 Cover vs ranged",
    },
    # Adventuring Gear
    {
        "name": "Backpack",
        "category": "Adventuring Gear",
        "cost": 50.0,
        "weight": 2.0,
        "min_str": None,
        "damage": None,
        "range": None,
        "armor_bonus": 0,
        "parry_bonus": 0,
        "notes": "Standard gear pack",
    },
    {
        "name": "Bedroll",
        "category": "Adventuring Gear",
        "cost": 25.0,
        "weight": 4.0,
        "min_str": None,
        "damage": None,
        "range": None,
        "armor_bonus": 0,
        "parry_bonus": 0,
        "notes": "",
    },
    {
        "name": "Rope",
        "category": "Adventuring Gear",
        "cost": 10.0,
        "weight": 10.0,
        "min_str": None,
        "damage": None,
        "range": None,
        "armor_bonus": 0,
        "parry_bonus": 0,
        "notes": "50 feet hemp",
    },
    {
        "name": "Flashlight",
        "category": "Adventuring Gear",
        "cost": 20.0,
        "weight": 1.0,
        "min_str": None,
        "damage": None,
        "range": None,
        "armor_bonus": 0,
        "parry_bonus": 0,
        "notes": "",
    },
    {
        "name": "Trail Rations",
        "category": "Adventuring Gear",
        "cost": 10.0,
        "weight": 1.0,
        "min_str": None,
        "damage": None,
        "range": None,
        "armor_bonus": 0,
        "parry_bonus": 0,
        "notes": "5 meals",
    },
    # Ammo
    {
        "name": "9mm Ammo",
        "category": "Ammo",
        "cost": 0.5,
        "weight": 0.05,
        "min_str": None,
        "damage": None,
        "range": None,
        "armor_bonus": 0,
        "parry_bonus": 0,
        "notes": "50 rounds box",
    },
    {
        "name": "Arrow",
        "category": "Ammo",
        "cost": 0.5,
        "weight": 0.1,
        "min_str": None,
        "damage": None,
        "range": None,
        "armor_bonus": 0,
        "parry_bonus": 0,
        "notes": "Quiver of 20",
    },
    {
        "name": ".45 Ammo",
        "category": "Ammo",
        "cost": 0.6,
        "weight": 0.06,
        "min_str": None,
        "damage": None,
        "range": None,
        "armor_bonus": 0,
        "parry_bonus": 0,
        "notes": "50 rounds box",
    },
]


def seed_default_catalog(conn: sqlite3.Connection) -> None:
    """Seed canonical SWADE equipment into catalog_items idempotently.

    Args:
        conn: SQLite connection with schema initialized.
    """
    insert_sql = """
    INSERT OR IGNORE INTO catalog_items (
        name, category, cost, weight, min_str, damage, range, armor_bonus, parry_bonus, notes
    ) VALUES (
        :name, :category, :cost, :weight, :min_str, :damage, :range, :armor_bonus, :parry_bonus, :notes
    );
    """
    with conn:
        conn.executemany(insert_sql, CANONICAL_CATALOG_ITEMS)
